"""
Materialize the FROZEN train/test split for the model-search loop, exactly as
defined in docs/model_loop_spec.md §1.1–1.3, and write a manifest with SHA-256
hashes so the split can never silently drift.

Run ONCE (owner, iteration 0). Deterministic (seed 42). Reads the all-routes
export; writes exports/loop_train.parquet, exports/loop_test.parquet, and
exports/loop_split_manifest.txt.

    venv/bin/python3 scripts/materialize_loop_split.py \
        --parquet exports/all_routes_2026-06-13.parquet

Split (frozen 2026-06-12, FIFA-corrected):
  TRAIN  service_date <= 2026-06-07, exclude anomaly + holdout routes,
         top-25 routes by count, 500 rows/route (seed 42)  [= fit_m3.R policy]
  TEST   service_date 2026-06-08..2026-06-11 (06-12 dropped: match-eve+partial),
         exclude the 6 anomaly routes, keep ALL others incl. holdouts 6641/6705,
         capped at 500 rows/route (seed 42) for tractable repeated ELPD eval.
"""
import argparse
import hashlib
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).parent.parent
EXPORT_DIR = ROOT / "exports"

TRAIN_MAX_DATE = "2026-06-07"
TEST_MIN_DATE  = "2026-06-08"
TEST_MAX_DATE  = "2026-06-11"          # 06-12 excluded (FIFA match-eve + partial day)

ANOMALY_ROUTES = ["12940", "6700", "30055", "6702", "6718", "6619"]
HOLDOUT_ROUTES = ["6641", "6705"]      # excluded from TRAIN only; present in TEST
SEED = 42
N_TRAIN_ROUTES = 25
N_PER_ROUTE    = 500


def _filtered(df: pd.DataFrame) -> pd.DataFrame:
    """Row filters shared by train and test (mirror fit_m3.R)."""
    df = df[
        (df["route_id"] != "")
        & df["delay_seconds"].notna()
        & df["previous_stop_delay"].notna()
        & df["shape_dist_traveled"].notna()
        & df["hour"].notna()
        & df["stop_id"].notna()
        & df["trip_id"].notna()
        & (df["delay_seconds"].abs() <= 3600)
        & (df["previous_stop_delay"].abs() <= 3600)
    ].copy()
    df["service_date"] = pd.to_datetime(
        df["timestamp"], format="ISO8601", utc=True
    ).dt.tz_convert("America/Vancouver").dt.strftime("%Y-%m-%d")
    return df


def _drop_anomaly_days(df: pd.DataFrame) -> pd.DataFrame:
    """fit_m3.R rule: drop days with n < 0.2*median(n) OR |mean-overall|>2*sd."""
    daily = df.groupby("service_date")["delay_seconds"].agg(["size", "mean"])
    overall_mean, overall_sd = daily["mean"].mean(), daily["mean"].std()
    bad = daily[
        (daily["size"] < 0.20 * daily["size"].median())
        | ((daily["mean"] - overall_mean).abs() > 2 * overall_sd)
    ].index.tolist()
    if bad:
        print(f"  anomaly days excluded: {', '.join(bad)}")
    return df[~df["service_date"].isin(bad)]


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(65536):
            h.update(chunk)
    return h.hexdigest()


def main(parquet: Path) -> None:
    rng_train = np.random.RandomState(SEED)
    rng_test  = np.random.RandomState(SEED)

    raw = pd.read_parquet(parquet)
    df = _drop_anomaly_days(_filtered(raw))
    df = df[~df["route_id"].isin(ANOMALY_ROUTES)]

    # ── TRAIN ────────────────────────────────────────────────────────────────
    train_pool = df[(df["service_date"] <= TRAIN_MAX_DATE)
                    & ~df["route_id"].isin(HOLDOUT_ROUTES)]
    counts = train_pool["route_id"].value_counts()
    top = counts[counts >= N_PER_ROUTE].head(N_TRAIN_ROUTES).index.tolist()
    train = (train_pool[train_pool["route_id"].isin(top)]
             .groupby("route_id", group_keys=False)
             .apply(lambda g: g.sample(n=N_PER_ROUTE, random_state=rng_train)))
    train = train.reset_index(drop=True)

    # ── TEST (frozen) ────────────────────────────────────────────────────────
    test_pool = df[(df["service_date"] >= TEST_MIN_DATE)
                   & (df["service_date"] <= TEST_MAX_DATE)]
    test = (test_pool.groupby("route_id", group_keys=False)
            .apply(lambda g: g.sample(n=min(len(g), N_PER_ROUTE), random_state=rng_test)))
    test = test.reset_index(drop=True)

    train_path = EXPORT_DIR / "loop_train.parquet"
    test_path  = EXPORT_DIR / "loop_test.parquet"
    train.to_parquet(train_path, index=False)
    test.to_parquet(test_path, index=False)

    # ── Manifest ─────────────────────────────────────────────────────────────
    lines = [
        "# Frozen loop split manifest — model_loop_spec.md §1.1 (FIFA-corrected)",
        f"# generated by scripts/materialize_loop_split.py  seed={SEED}",
        f"source_parquet: {parquet.name}",
        f"train_window: <= {TRAIN_MAX_DATE}   test_window: {TEST_MIN_DATE}..{TEST_MAX_DATE}",
        f"anomaly_routes_excluded: {','.join(ANOMALY_ROUTES)}",
        f"holdout_routes (train-excluded, test-present): {','.join(HOLDOUT_ROUTES)}",
        "",
        f"loop_train.parquet  rows={len(train):<7} routes={train['route_id'].nunique():<4} "
        f"dates={train['service_date'].min()}..{train['service_date'].max()}",
        f"  sha256={_sha256(train_path)}",
        f"loop_test.parquet   rows={len(test):<7} routes={test['route_id'].nunique():<4} "
        f"dates={test['service_date'].min()}..{test['service_date'].max()}",
        f"  sha256={_sha256(test_path)}",
        "",
        "# The loop must verify these hashes before each iteration and ABORT if",
        "# either parquet changed (model_loop_spec.md §3 STOP conditions).",
    ]
    manifest = EXPORT_DIR / "loop_split_manifest.txt"
    manifest.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {train_path.name}, {test_path.name}, {manifest.name}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--parquet", type=Path, required=True,
                   help="all-routes export (covers train+test windows)")
    main(p.parse_args().parquet)
