# ─────────────────────────────────────────────────────────────────────────────
# FIXED SCAFFOLD for a model-search loop candidate.
# The loop agent COPIES this to analysis/fit_candidate_<ID>.R and edits ONLY the
# three clearly-marked blocks (CANDIDATE_ID, the formula, optional data tweak).
# Everything else — the frozen split, priors, sampler settings, the held-out
# ELPD/RMSE/coverage evaluation, and the run_log row — stays identical across
# candidates so model structure is the only thing that varies (model_loop_spec.md).
#
# Reads:  exports/loop_train.parquet, exports/loop_test.parquet  (FROZEN — never
#         regenerated by the loop; hashes verified by run_loop_iteration.sh).
# Writes: analysis/models/brms_<ID>.rds, exports/loglik_<ID>.rds (pointwise test
#         log-lik for ΔELPD±SE), one row appended to exports/run_log.csv.
# ─────────────────────────────────────────────────────────────────────────────
suppressMessages({
  library(brms); library(arrow); library(dplyr); library(lubridate); library(loo)
})
options(mc.cores = parallel::detectCores())

# ===== EDIT 1 OF 3: candidate id ============================================
CANDIDATE_ID <- "TEMPLATE"   # e.g. "C0", "C2", ...
# ============================================================================

train <- arrow::read_parquet("../exports/loop_train.parquet") |>
  mutate(trip_id = as.character(trip_id), stop_id = as.character(stop_id),
         route_id = as.character(route_id), hour = as.integer(hour), dow = as.integer(dow))
test  <- arrow::read_parquet("../exports/loop_test.parquet") |>
  mutate(trip_id = as.character(trip_id), stop_id = as.character(stop_id),
         route_id = as.character(route_id), hour = as.integer(hour), dow = as.integer(dow))
stopifnot(nrow(test) >= 100)

# ===== EDIT 2 OF 3: any candidate-specific data prep (default: none) =========
# e.g. C1: train <- filter(train, settled == 1)
#      C2: add headway columns; etc. Leave empty for pure-formula candidates.
# ============================================================================

# ===== EDIT 3 OF 3: the formula (model_loop_spec.md §4) ======================
# Default = m3 baseline. adapt_delta default 0.95; C0 raises it to 0.99.
f_cand <- bf(
  delay_seconds ~ previous_stop_delay + shape_dist_traveled +
    s(hour, bs = "cc", k = 8) + s(dow, bs = "cc", k = 5) +
    (1 | route_id) + (1 | trip_id) + (1 | stop_id)
)
ADAPT_DELTA <- 0.95
# ============================================================================

base_priors <- c(
  prior(normal(0, 2),   class = b),
  prior(normal(0, 10),  class = Intercept),
  prior(exponential(1), class = sigma),
  prior(exponential(1), class = sd),
  prior(gamma(2, 0.1),  class = nu, lb = 2)
)

cat(sprintf("Fitting %s — train=%d test=%d\n", CANDIDATE_ID, nrow(train), nrow(test)))
fit <- brm(
  f_cand, data = train, family = student(), prior = base_priors,
  knots = list(hour = c(0, 24), dow = c(0.5, 7.5)),
  iter = 2000, warmup = 1000, chains = 4, seed = 42,
  control = list(adapt_delta = ADAPT_DELTA),
  file = sprintf("models/brms_%s", CANDIDATE_ID),
  file_refit = "always",      # NEVER silently reload a cached fit (registry caveat #1)
  refresh = 50
)

# ── Convergence gate inputs (model_loop_spec.md / baseline_registry.md §4) ────
rhat_max <- max(brms::rhat(fit), na.rm = TRUE)
np       <- bayesplot::nuts_params(fit)
n_div    <- sum(np$Value[np$Parameter == "divergent__"])
cat(sprintf("%s rhat_max=%.4f  divergences=%d\n", CANDIDATE_ID, rhat_max, n_div))

# ── Held-out eval + run_log row, MEMORY-SAFE (16 GB: full-set ELPD via log_lik,
#    freed before a chunked posterior_predict for RMSE/coverage). See loop_eval.R.
#    A whole-matrix eval OOMs on the 104k-row frozen test set on this machine.
source("loop_eval.R")
eval_and_log(fit, CANDIDATE_ID, train, test,
             model_file = sprintf("models/brms_%s.rds (loop %s, frozen test)", CANDIDATE_ID, CANDIDATE_ID))
cat(sprintf("%s logged to run_log.csv\n", CANDIDATE_ID))
