# ─────────────────────────────────────────────────────────────────────────────
# FIXED SCAFFOLD for a model-search loop candidate.
# The loop agent COPIES this to analysis/fit_candidate_<ID>.R and edits ONLY the
# three clearly-marked blocks (CANDIDATE_ID, the formula, optional data tweak).
# Everything else — the frozen split, priors, sampler settings, the held-out
# ELPD/RMSE/coverage evaluation, and the run_log row — stays identical across
# candidates so model structure is the only thing that varies (model_loop_spec.md).
#
# Reads:  exports/loop_train.parquet, exports/loop_test.parquet  (FROZEN — never
#         regenerated by the loop; hashes verified by run_loop_iteration.sh).
# Writes: analysis/models/brms_<ID>.rds, exports/loglik_<ID>.rds (pointwise test
#         log-lik for ΔELPD±SE), one row appended to exports/run_log.csv.
# ─────────────────────────────────────────────────────────────────────────────
suppressMessages({
  library(brms); library(arrow); library(dplyr); library(lubridate); library(loo)
})
options(mc.cores = parallel::detectCores())

# ===== EDIT 1 OF 3: candidate id ============================================
CANDIDATE_ID <- "C0_notrip"   # diagnostic: m3 with (1|trip_id) REMOVED, all else identical
# ============================================================================

train <- arrow::read_parquet("../exports/loop_train.parquet") |>
  mutate(trip_id = as.character(trip_id), stop_id = as.character(stop_id),
         route_id = as.character(route_id), hour = as.integer(hour), dow = as.integer(dow))
test  <- arrow::read_parquet("../exports/loop_test.parquet") |>
  mutate(trip_id = as.character(trip_id), stop_id = as.character(stop_id),
         route_id = as.character(route_id), hour = as.integer(hour), dow = as.integer(dow))
stopifnot(nrow(test) >= 100)

# ===== EDIT 2 OF 3: any candidate-specific data prep (default: none) =========
# e.g. C1: train <- filter(train, settled == 1)
#      C2: add headway columns; etc. Leave empty for pure-formula candidates.
# ============================================================================

# ===== EDIT 3 OF 3: the formula (model_loop_spec.md §4) ======================
# DIAGNOSTIC: m3 base with (1|trip_id) REMOVED — the ONLY change from m3.
# Tests whether the ~5,500-level near-observation-level trip RE (~1.4 obs/level,
# funnel geometry) is what breaks m3's convergence. Likelihood, both remaining
# group terms, fixed effects, splines, priors, and adapt_delta all UNCHANGED
# (default 0.95) so the trip term is the sole confound this round.
f_cand <- bf(
  delay_seconds ~ previous_stop_delay + shape_dist_traveled +
    s(hour, bs = "cc", k = 8) + s(dow, bs = "cc", k = 5) +
    (1 | route_id) + (1 | stop_id)
)
ADAPT_DELTA <- 0.95
# ============================================================================

base_priors <- c(
  prior(normal(0, 2),   class = b),
  prior(normal(0, 10),  class = Intercept),
  prior(exponential(1), class = sigma),
  prior(exponential(1), class = sd),
  prior(gamma(2, 0.1),  class = nu, lb = 2)
)

cat(sprintf("Fitting %s — train=%d test=%d\n", CANDIDATE_ID, nrow(train), nrow(test)))
fit <- brm(
  f_cand, data = train, family = student(), prior = base_priors,
  knots = list(hour = c(0, 24), dow = c(0.5, 7.5)),
  iter = 2000, warmup = 1000, chains = 4, seed = 42,
  control = list(adapt_delta = ADAPT_DELTA),
  file = sprintf("models/brms_%s", CANDIDATE_ID),
  file_refit = "always",      # NEVER silently reload a cached fit (registry caveat #1)
  refresh = 50
)

# ── Convergence gate inputs (model_loop_spec.md / baseline_registry.md §4) ────
rhat_max <- max(brms::rhat(fit), na.rm = TRUE)
np       <- bayesplot::nuts_params(fit)
n_div    <- sum(np$Value[np$Parameter == "divergent__"])
cat(sprintf("%s rhat_max=%.4f  divergences=%d\n", CANDIDATE_ID, rhat_max, n_div))

# ── Held-out evaluation on the FROZEN test set ───────────────────────────────
# Pointwise test log-lik → ELPD (and ΔELPD±SE vs the saved baseline pointwise).
ll <- log_lik(fit, newdata = test, allow_new_levels = TRUE, sample_new_levels = "gaussian")
saveRDS(ll, sprintf("../exports/loglik_%s.rds", CANDIDATE_ID))
elpd_obj <- loo::elpd(ll)
cat(sprintf("%s held-out ELPD=%.1f (SE %.1f)\n",
            CANDIDATE_ID, elpd_obj$estimates["elpd", "Estimate"],
            elpd_obj$estimates["elpd", "SE"]))
base_ll <- "../exports/loglik_C0.rds"
if (file.exists(base_ll) && CANDIDATE_ID != "C0") {
  cmp <- loo::loo_compare(loo::elpd(readRDS(base_ll)), elpd_obj)
  cat("ΔELPD vs C0 (loo_compare):\n"); print(cmp)
}

pred <- posterior_predict(fit, newdata = test, allow_new_levels = TRUE,
                          sample_new_levels = "gaussian")
mu <- colMeans(pred)
lo <- apply(pred, 2, quantile, 0.05); hi <- apply(pred, 2, quantile, 0.95)
results <- test |>
  mutate(pred = mu, residual = delay_seconds - mu,
         covered = delay_seconds >= lo & delay_seconds <= hi)
cat(sprintf("%s MAE=%.2f RMSE=%.2f cov90=%.4f\n", CANDIDATE_ID,
            mean(abs(results$residual)), sqrt(mean(results$residual^2)),
            mean(results$covered)))

# ── Append a run_log row (loop memory). model_file embeds the id so
#    run_loop_iteration.sh sees this candidate as "done". ───────────────────
source("run_tracker.R")
track_run(model = fit, train_df = train, test_df = test, results = results,
          model_file = sprintf("models/brms_%s.rds (loop %s, frozen test)", CANDIDATE_ID, CANDIDATE_ID),
          n_routes = dplyr::n_distinct(train$route_id))
cat(sprintf("%s logged to run_log.csv\n", CANDIDATE_ID))
